spring:
  mail:
    host: localhost
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 1025
          auth: false
          starttls:
            enable: false
            required: false
  data:
    mongodb:
      database: emailretry
      port: 27017
      host: localhost
cron:
  expression: "0 0/5 * * * *"
retry:
  initialinterval: 5000
  multiplier: 2
  maxinterval: 80000